#ifndef SKYBOX_H
#define SKYBOX_H

//#define WIN32_LEAN_AND_MEAN
//#define WIN32_EXTRA_LEAN

/*
	skybox.h
	
	The Skybox class.  Use it to make a sky box that seems to be at 
	 infinite distance, because it moves with you

    Note that the argument to "load" is a directory.  That directory MUST contain
	the files "Front.bmp", "Left.bmp", "Back.bmp", "Right.bmp", "Top.bmp"

	These are generated by the program to build sky box BMP's at ??

	
*/

#include "worldCoord.h"
#include "texture.h"

using namespace lcgl;

class Skybox
{
private:
	enum {FACES = 5 }; //we don't use the bottom face, so it's not 6
	
	Texture2D _faces [FACES]; 
public:
	Skybox (const char* directory);

	void render(const worldCoord& pov) const;
};

#endif